//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerApplication.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Customer_Infoo
    {
        public int Customer_Id { get; set; }
        [Required(ErrorMessage = "First Name Required")]
        public string First_Name { get; set; }
        [Required(ErrorMessage = "Second Name Required")]
        public string Second_Name { get; set; }

        [Required(ErrorMessage = "Email is required")]
        [EmailAddress]
        public string Email { get; set; }

        [Required(ErrorMessage = "Gender Required")]
        public string Gender { get; set; }

        [MinLength(10,ErrorMessage ="Contact should be atleast 10 digits")]
        
        public string Phone { get; set; }
        
        [Required(ErrorMessage = "Address1 is required")]
        public string Address1 { get; set; }
        
        public string Address2 { get; set; }

        [Required(ErrorMessage = "City is required")]
        public string City { get; set; }
        [Required(ErrorMessage = "State is required")]
        public string State { get; set; }
        [Required(ErrorMessage = "Country Name Required")]
       public string Country { get; set; }
        public Nullable<bool> isBusiness { get; set; }
        public Nullable<bool> isDelivery { get; set; }
        public Nullable<bool> isVisiting { get; set; }
        public Nullable<bool> isOther { get; set; }
    }
}
